
//Set path to SmartSlog KP Library
#include <smartslog.h>

#ifndef _GENERATED_ONTOLOGY
#define	_GENERATED_ONTOLOGY


#ifdef	__cplusplus
extern "C" {
#endif


#define INCLUDE_ALL_ONT_ENTITIES 1
#ifdef INCLUDE_ALL_ONT_ENTITIES

#define INCLUDE_PROPERTY_HASSTATIONAREQUIPMENT 1
#define INCLUDE_PROPERTY_TAKEDRUGTIME 1
#define INCLUDE_PROPERTY_HASPATIENTMAP 1
#define INCLUDE_PROPERTY_EXAMINATIONREASON 1
#define INCLUDE_PROPERTY_RESPONSETOALARM 1
#define INCLUDE_PROPERTY_ISPATIENTDRUGADDICTED 1
#define INCLUDE_PROPERTY_RESPONSEFILEURI 1
#define INCLUDE_PROPERTY_QUESTIONNAIREURI 1
#define INCLUDE_PROPERTY_LEFTBIPOLAR 1
#define INCLUDE_PROPERTY_USEEQUIPMENTTIME 1
#define INCLUDE_PROPERTY_USERNAME 1
#define INCLUDE_PROPERTY_DATALOCATION 1
#define INCLUDE_PROPERTY_FIELDNAME 1
#define INCLUDE_PROPERTY_ISONLINE 1
#define INCLUDE_PROPERTY_EQUIPPARAMETER 1
#define INCLUDE_PROPERTY_SEX 1
#define INCLUDE_PROPERTY_PASSAUTH 1
#define INCLUDE_PROPERTY_HASDRUGTOSAVE 1
#define INCLUDE_PROPERTY_FREEPATIENTCAPACITY 1
#define INCLUDE_PROPERTY_IMG 1
#define INCLUDE_PROPERTY_HASDOCTOR 1
#define INCLUDE_PROPERTY_RELATESTO 1
#define INCLUDE_PROPERTY_READYTOHELP 1
#define INCLUDE_PROPERTY_CONTAINSSUBRESPONSE 1
#define INCLUDE_PROPERTY_CONTAINSFILE 1
#define INCLUDE_PROPERTY_PATIENTWEIGHT 1
#define INCLUDE_PROPERTY_TOPDATAPROPERTY 1
#define INCLUDE_PROPERTY_HOSPITALNAME 1
#define INCLUDE_PROPERTY_HEIGHT 1
#define INCLUDE_PROPERTY_RESIDENCE 1
#define INCLUDE_PROPERTY_DRINKING 1
#define INCLUDE_PROPERTY_CARNUMBER 1
#define INCLUDE_PROPERTY_ITEMTEXT 1
#define INCLUDE_PROPERTY_SMOKING 1
#define INCLUDE_PROPERTY_SENDALARM 1
#define INCLUDE_PROPERTY_HASDRUGTOMEDICINE 1
#define INCLUDE_PROPERTY_FEEDBACKURI 1
#define INCLUDE_PROPERTY_SPECIALLITY 1
#define INCLUDE_PROPERTY_HASQUESTION 1
#define INCLUDE_PROPERTY_ADVICETEXT 1
#define INCLUDE_PROPERTY_LOCATION 1
#define INCLUDE_PROPERTY_HASDRUGTOTAKE 1
#define INCLUDE_PROPERTY_HASMEDICALRECORDSCARD 1
#define INCLUDE_PROPERTY_MEDICATIONS 1
#define INCLUDE_PROPERTY_HASACCESS 1
#define INCLUDE_PROPERTY_MULTIPLEITEM 1
#define INCLUDE_PROPERTY_CONTAINECGSURVEYS 1
#define INCLUDE_PROPERTY_DICHOTOMOUSITEM 1
#define INCLUDE_PROPERTY_HASRESPONSEITEM 1
#define INCLUDE_PROPERTY_RIGHTBIPOLAR 1
#define INCLUDE_PROPERTY_DRUGNAME 1
#define INCLUDE_PROPERTY_SENDADVICE 1
#define INCLUDE_PROPERTY_CONTACTINFORMATION 1
#define INCLUDE_PROPERTY_HASDOCUMENT 1
#define INCLUDE_PROPERTY_ISPATIENTMEDICINEADDICTED 1
#define INCLUDE_PROPERTY_SEARCHSTRING 1
#define INCLUDE_PROPERTY_SERVEYDATE 1
#define INCLUDE_PROPERTY_HEMATOCRIT 1
#define INCLUDE_PROPERTY_AGE 1
#define INCLUDE_PROPERTY_ALARMSTATUS 1
#define INCLUDE_PROPERTY_DRUGANNOTATION 1
#define INCLUDE_PROPERTY_PATIENTBLOODTYPE 1
#define INCLUDE_PROPERTY_PHARMNAME 1
#define INCLUDE_PROPERTY_ITEMSCORE 1
#define INCLUDE_PROPERTY_HASFEEDBACK 1
#define INCLUDE_PROPERTY_HASPERSLOCATION 1
#define INCLUDE_PROPERTY_ORGANIZATIONNAME 1
#define INCLUDE_PROPERTY_PATIENTRHFACTOR 1
#define INCLUDE_PROPERTY_SURVEYECGINFO 1
#define INCLUDE_PROPERTY_CONTAINUSHSURVEYS 1
#define INCLUDE_PROPERTY_REQUESTSDOCUMENT 1
#define INCLUDE_PROPERTY_SINGLEITEM 1
#define INCLUDE_PROPERTY_PATRONYMIC 1
#define INCLUDE_PROPERTY_HASAMBLOCATION 1
#define INCLUDE_PROPERTY_DISEASEDESCRIPTION 1
#define INCLUDE_PROPERTY_HASDRUGTOSALE 1
#define INCLUDE_PROPERTY_DATEFROM 1
#define INCLUDE_PROPERTY_TOPOBJECTPROPERTY 1
#define INCLUDE_PROPERTY_HEMOGLOBIN 1
#define INCLUDE_PROPERTY_CONTAINSTEXT 1
#define INCLUDE_PROPERTY_SERVEYRESULT 1
#define INCLUDE_PROPERTY_PATIENTHEIGHT 1
#define INCLUDE_PROPERTY_WORKHOSPITAL 1
#define INCLUDE_PROPERTY_PHONE 1
#define INCLUDE_PROPERTY_ALARMTIME 1
#define INCLUDE_PROPERTY_HASHOSPLOCATION 1
#define INCLUDE_PROPERTY_SUBANSWER 1
#define INCLUDE_PROPERTY_DIAGNOSES 1
#define INCLUDE_PROPERTY_RANGINGITEM 1
#define INCLUDE_PROPERTY_HASREQUEST 1
#define INCLUDE_PROPERTY_PULSE 1
#define INCLUDE_PROPERTY_CODE 1
#define INCLUDE_PROPERTY_RESPONDEDTO 1
#define INCLUDE_PROPERTY_DISEASEPREDISPOSITION 1
#define INCLUDE_PROPERTY_DESCRIPTION 1
#define INCLUDE_PROPERTY_HASANSWER 1
#define INCLUDE_PROPERTY_HASPHARMLOCATION 1
#define INCLUDE_PROPERTY_SERVEYDATALINK 1
#define INCLUDE_PROPERTY_CREATEDAT 1
#define INCLUDE_PROPERTY_ISPATIENTSMOKE 1
#define INCLUDE_PROPERTY_AUTHOR 1
#define INCLUDE_PROPERTY_VISITORDER 1
#define INCLUDE_PROPERTY_DIASTOLICPRESSURE 1
#define INCLUDE_PROPERTY_SYSTOLICPRESSURE 1
#define INCLUDE_PROPERTY_BELONGSTO 1
#define INCLUDE_PROPERTY_HASPATIENTMETRICS 1
#define INCLUDE_PROPERTY_DOSAGE 1
#define INCLUDE_PROPERTY_LINKEDWITHITEM 1
#define INCLUDE_PROPERTY_SERVEYTYPE 1
#define INCLUDE_PROPERTY_DOCUMENTNUMBERFULL 1
#define INCLUDE_PROPERTY_LONG 1
#define INCLUDE_PROPERTY_HISID 1
#define INCLUDE_PROPERTY_FIRSTQUESTION 1
#define INCLUDE_PROPERTY_ANWEREDTO 1
#define INCLUDE_PROPERTY_ISPATIENTALCOHOLADDICTED 1
#define INCLUDE_PROPERTY_SERVEYDESCRIPTION 1
#define INCLUDE_PROPERTY_DOCUMENTTYPE 1
#define INCLUDE_PROPERTY_LAT 1
#define INCLUDE_PROPERTY_SURNAME 1
#define INCLUDE_PROPERTY_HASRESPONSE 1
#define INCLUDE_PROPERTY_DOCUMENTRELEASEDATE 1
#define INCLUDE_PROPERTY_PERSONINFORMATION 1
#define INCLUDE_PROPERTY_AUTHREQUESTSTATUS 1
#define INCLUDE_PROPERTY_RESPONSETEXT 1
#define INCLUDE_PROPERTY_PASSWORD 1
#define INCLUDE_PROPERTY_WEIGHT 1
#define INCLUDE_PROPERTY_BIRTHDATE 1
#define INCLUDE_PROPERTY_MBOX 1
#define INCLUDE_PROPERTY_HASPORTABLEEQUIPMENT 1
#define INCLUDE_PROPERTY_DESCRIBES 1
#define INCLUDE_PROPERTY_VERSION 1
#define INCLUDE_PROPERTY_DATETO 1
#define INCLUDE_PROPERTY_WORKAMBULANCE 1
#define INCLUDE_PROPERTY_NEXTQUESTION 1
#define INCLUDE_PROPERTY_FEEDBACKDATE 1
#define INCLUDE_PROPERTY_NAME 1
#define INCLUDE_PROPERTY_HASERROR 1
#define INCLUDE_PROPERTY_STATUS 1
#define INCLUDE_PROPERTY_ADVICETIME 1
#define INCLUDE_PROPERTY_ERYTHROCYTE 1
#define INCLUDE_PROPERTY_DISEASETYPE 1
#define INCLUDE_PROPERTY_SERVEYUSHINFO 1
#define INCLUDE_PROPERTY_CONTAINDISEASES 1
#define INCLUDE_CLASS_RANGINGSCALE 1
#define INCLUDE_CLASS_QUESTIONNAIRE 1
#define INCLUDE_CLASS_THING 1
#define INCLUDE_CLASS_ALARM 1
#define INCLUDE_CLASS_RESPONSETEXT 1
#define INCLUDE_CLASS_LOCATION 1
#define INCLUDE_CLASS_DICHOTOMOUS 1
#define INCLUDE_CLASS_HISREQUEST 1
#define INCLUDE_CLASS_CHOISE 1
#define INCLUDE_CLASS_PATIENTMETRICS 1
#define INCLUDE_CLASS_FEEDBACK 1
#define INCLUDE_CLASS_PHARMACY 1
#define INCLUDE_CLASS_GUTTMANSCALE 1
#define INCLUDE_CLASS_RESPONSEFILE 1
#define INCLUDE_CLASS_HISDOCUMENT 1
#define INCLUDE_CLASS_LABORATORYANALYSIS 1
#define INCLUDE_CLASS_RESPONSE 1
#define INCLUDE_CLASS_HISRESPONSE 1
#define INCLUDE_CLASS_DOCUMENT 1
#define INCLUDE_CLASS_BED 1
#define INCLUDE_CLASS_MEDIC 1
#define INCLUDE_CLASS_BLOODPRESSUREMEASUREMENT 1
#define INCLUDE_CLASS_ECGMEASUREMENT 1
#define INCLUDE_CLASS_USHSERVEY 1
#define INCLUDE_CLASS_CARING 1
#define INCLUDE_CLASS_PHONE 1
#define INCLUDE_CLASS_AMBULANCE 1
#define INCLUDE_CLASS_CLOSEDANSWER 1
#define INCLUDE_CLASS_HOSPITALINFORMATIONSYSTEM 1
#define INCLUDE_CLASS_DOCTOREXAMINATION 1
#define INCLUDE_CLASS_RESPONSEITEM 1
#define INCLUDE_CLASS_PATIENT 1
#define INCLUDE_CLASS_PERSON 1
#define INCLUDE_CLASS_AUTHREQUEST 1
#define INCLUDE_CLASS_PHOTO 1
#define INCLUDE_CLASS_DOCTOR 1
#define INCLUDE_CLASS_NURSE 1
#define INCLUDE_CLASS_LIKERTSCALE 1
#define INCLUDE_CLASS_AUDIO 1
#define INCLUDE_CLASS_CONTINUOUSSCALE 1
#define INCLUDE_CLASS_FILE 1
#define INCLUDE_CLASS_ADVICE 1
#define INCLUDE_CLASS_TEXT 1
#define INCLUDE_CLASS_MEDICALRECORDSCARD 1
#define INCLUDE_CLASS_ANSWER 1
#define INCLUDE_CLASS_NOTHING 1
#define INCLUDE_CLASS_MULTIPLECHOISE 1
#define INCLUDE_CLASS_ITEM 1
#define INCLUDE_CLASS_HOSPITAL 1
#define INCLUDE_CLASS_SERVEY 1
#define INCLUDE_CLASS_PROFILE 1
#define INCLUDE_CLASS_NUMBER 1
#define INCLUDE_CLASS_MEASUREMENT 1
#define INCLUDE_CLASS_VIDEO 1
#define INCLUDE_CLASS_DISEASE 1
#define INCLUDE_CLASS_ECGSERVEY 1
#define INCLUDE_CLASS_OPENANSWER 1
#define INCLUDE_CLASS_PATIENTMAP 1
#define INCLUDE_CLASS_QUESTION 1
#define INCLUDE_CLASS_DEMOGRAPHICDATA 1
#define INCLUDE_CLASS_EQUIPMENT 1
#define INCLUDE_CLASS_DRUG 1
#define INCLUDE_CLASS_SINGLECHOISE 1
#define INCLUDE_CLASS_VALIDATED 1
#define INCLUDE_CLASS_EMAIL 1
#define INCLUDE_CLASS_BIPOLARQUESTION 1


#else

#define INCLUDE_PROPERTY_HASSTATIONAREQUIPMENT 0
#define INCLUDE_PROPERTY_TAKEDRUGTIME 0
#define INCLUDE_PROPERTY_HASPATIENTMAP 0
#define INCLUDE_PROPERTY_EXAMINATIONREASON 0
#define INCLUDE_PROPERTY_RESPONSETOALARM 0
#define INCLUDE_PROPERTY_ISPATIENTDRUGADDICTED 0
#define INCLUDE_PROPERTY_RESPONSEFILEURI 0
#define INCLUDE_PROPERTY_QUESTIONNAIREURI 0
#define INCLUDE_PROPERTY_LEFTBIPOLAR 0
#define INCLUDE_PROPERTY_USEEQUIPMENTTIME 0
#define INCLUDE_PROPERTY_USERNAME 0
#define INCLUDE_PROPERTY_DATALOCATION 0
#define INCLUDE_PROPERTY_FIELDNAME 0
#define INCLUDE_PROPERTY_ISONLINE 0
#define INCLUDE_PROPERTY_EQUIPPARAMETER 0
#define INCLUDE_PROPERTY_SEX 0
#define INCLUDE_PROPERTY_PASSAUTH 0
#define INCLUDE_PROPERTY_HASDRUGTOSAVE 0
#define INCLUDE_PROPERTY_FREEPATIENTCAPACITY 0
#define INCLUDE_PROPERTY_IMG 0
#define INCLUDE_PROPERTY_HASDOCTOR 0
#define INCLUDE_PROPERTY_RELATESTO 0
#define INCLUDE_PROPERTY_READYTOHELP 0
#define INCLUDE_PROPERTY_CONTAINSSUBRESPONSE 0
#define INCLUDE_PROPERTY_CONTAINSFILE 0
#define INCLUDE_PROPERTY_PATIENTWEIGHT 0
#define INCLUDE_PROPERTY_TOPDATAPROPERTY 0
#define INCLUDE_PROPERTY_HOSPITALNAME 0
#define INCLUDE_PROPERTY_HEIGHT 0
#define INCLUDE_PROPERTY_RESIDENCE 0
#define INCLUDE_PROPERTY_DRINKING 0
#define INCLUDE_PROPERTY_CARNUMBER 0
#define INCLUDE_PROPERTY_ITEMTEXT 0
#define INCLUDE_PROPERTY_SMOKING 0
#define INCLUDE_PROPERTY_SENDALARM 0
#define INCLUDE_PROPERTY_HASDRUGTOMEDICINE 0
#define INCLUDE_PROPERTY_FEEDBACKURI 0
#define INCLUDE_PROPERTY_SPECIALLITY 0
#define INCLUDE_PROPERTY_HASQUESTION 0
#define INCLUDE_PROPERTY_ADVICETEXT 0
#define INCLUDE_PROPERTY_LOCATION 0
#define INCLUDE_PROPERTY_HASDRUGTOTAKE 0
#define INCLUDE_PROPERTY_HASMEDICALRECORDSCARD 0
#define INCLUDE_PROPERTY_MEDICATIONS 0
#define INCLUDE_PROPERTY_HASACCESS 0
#define INCLUDE_PROPERTY_MULTIPLEITEM 0
#define INCLUDE_PROPERTY_CONTAINECGSURVEYS 0
#define INCLUDE_PROPERTY_DICHOTOMOUSITEM 0
#define INCLUDE_PROPERTY_HASRESPONSEITEM 0
#define INCLUDE_PROPERTY_RIGHTBIPOLAR 0
#define INCLUDE_PROPERTY_DRUGNAME 0
#define INCLUDE_PROPERTY_SENDADVICE 0
#define INCLUDE_PROPERTY_CONTACTINFORMATION 0
#define INCLUDE_PROPERTY_HASDOCUMENT 0
#define INCLUDE_PROPERTY_ISPATIENTMEDICINEADDICTED 0
#define INCLUDE_PROPERTY_SEARCHSTRING 0
#define INCLUDE_PROPERTY_SERVEYDATE 0
#define INCLUDE_PROPERTY_HEMATOCRIT 0
#define INCLUDE_PROPERTY_AGE 0
#define INCLUDE_PROPERTY_ALARMSTATUS 0
#define INCLUDE_PROPERTY_DRUGANNOTATION 0
#define INCLUDE_PROPERTY_PATIENTBLOODTYPE 0
#define INCLUDE_PROPERTY_PHARMNAME 0
#define INCLUDE_PROPERTY_ITEMSCORE 0
#define INCLUDE_PROPERTY_HASFEEDBACK 0
#define INCLUDE_PROPERTY_HASPERSLOCATION 0
#define INCLUDE_PROPERTY_ORGANIZATIONNAME 0
#define INCLUDE_PROPERTY_PATIENTRHFACTOR 0
#define INCLUDE_PROPERTY_SURVEYECGINFO 0
#define INCLUDE_PROPERTY_CONTAINUSHSURVEYS 0
#define INCLUDE_PROPERTY_REQUESTSDOCUMENT 0
#define INCLUDE_PROPERTY_SINGLEITEM 0
#define INCLUDE_PROPERTY_PATRONYMIC 0
#define INCLUDE_PROPERTY_HASAMBLOCATION 0
#define INCLUDE_PROPERTY_DISEASEDESCRIPTION 0
#define INCLUDE_PROPERTY_HASDRUGTOSALE 0
#define INCLUDE_PROPERTY_DATEFROM 0
#define INCLUDE_PROPERTY_TOPOBJECTPROPERTY 0
#define INCLUDE_PROPERTY_HEMOGLOBIN 0
#define INCLUDE_PROPERTY_CONTAINSTEXT 0
#define INCLUDE_PROPERTY_SERVEYRESULT 0
#define INCLUDE_PROPERTY_PATIENTHEIGHT 0
#define INCLUDE_PROPERTY_WORKHOSPITAL 0
#define INCLUDE_PROPERTY_PHONE 0
#define INCLUDE_PROPERTY_ALARMTIME 0
#define INCLUDE_PROPERTY_HASHOSPLOCATION 0
#define INCLUDE_PROPERTY_SUBANSWER 0
#define INCLUDE_PROPERTY_DIAGNOSES 0
#define INCLUDE_PROPERTY_RANGINGITEM 0
#define INCLUDE_PROPERTY_HASREQUEST 0
#define INCLUDE_PROPERTY_PULSE 0
#define INCLUDE_PROPERTY_CODE 0
#define INCLUDE_PROPERTY_RESPONDEDTO 0
#define INCLUDE_PROPERTY_DISEASEPREDISPOSITION 0
#define INCLUDE_PROPERTY_DESCRIPTION 0
#define INCLUDE_PROPERTY_HASANSWER 0
#define INCLUDE_PROPERTY_HASPHARMLOCATION 0
#define INCLUDE_PROPERTY_SERVEYDATALINK 0
#define INCLUDE_PROPERTY_CREATEDAT 0
#define INCLUDE_PROPERTY_ISPATIENTSMOKE 0
#define INCLUDE_PROPERTY_AUTHOR 0
#define INCLUDE_PROPERTY_VISITORDER 0
#define INCLUDE_PROPERTY_DIASTOLICPRESSURE 0
#define INCLUDE_PROPERTY_SYSTOLICPRESSURE 0
#define INCLUDE_PROPERTY_BELONGSTO 0
#define INCLUDE_PROPERTY_HASPATIENTMETRICS 0
#define INCLUDE_PROPERTY_DOSAGE 0
#define INCLUDE_PROPERTY_LINKEDWITHITEM 0
#define INCLUDE_PROPERTY_SERVEYTYPE 0
#define INCLUDE_PROPERTY_DOCUMENTNUMBERFULL 0
#define INCLUDE_PROPERTY_LONG 0
#define INCLUDE_PROPERTY_HISID 0
#define INCLUDE_PROPERTY_FIRSTQUESTION 0
#define INCLUDE_PROPERTY_ANWEREDTO 0
#define INCLUDE_PROPERTY_ISPATIENTALCOHOLADDICTED 0
#define INCLUDE_PROPERTY_SERVEYDESCRIPTION 0
#define INCLUDE_PROPERTY_DOCUMENTTYPE 0
#define INCLUDE_PROPERTY_LAT 0
#define INCLUDE_PROPERTY_SURNAME 0
#define INCLUDE_PROPERTY_HASRESPONSE 0
#define INCLUDE_PROPERTY_DOCUMENTRELEASEDATE 0
#define INCLUDE_PROPERTY_PERSONINFORMATION 0
#define INCLUDE_PROPERTY_AUTHREQUESTSTATUS 0
#define INCLUDE_PROPERTY_RESPONSETEXT 0
#define INCLUDE_PROPERTY_PASSWORD 0
#define INCLUDE_PROPERTY_WEIGHT 0
#define INCLUDE_PROPERTY_BIRTHDATE 0
#define INCLUDE_PROPERTY_MBOX 0
#define INCLUDE_PROPERTY_HASPORTABLEEQUIPMENT 0
#define INCLUDE_PROPERTY_DESCRIBES 0
#define INCLUDE_PROPERTY_VERSION 0
#define INCLUDE_PROPERTY_DATETO 0
#define INCLUDE_PROPERTY_WORKAMBULANCE 0
#define INCLUDE_PROPERTY_NEXTQUESTION 0
#define INCLUDE_PROPERTY_FEEDBACKDATE 0
#define INCLUDE_PROPERTY_NAME 0
#define INCLUDE_PROPERTY_HASERROR 0
#define INCLUDE_PROPERTY_STATUS 0
#define INCLUDE_PROPERTY_ADVICETIME 0
#define INCLUDE_PROPERTY_ERYTHROCYTE 0
#define INCLUDE_PROPERTY_DISEASETYPE 0
#define INCLUDE_PROPERTY_SERVEYUSHINFO 0
#define INCLUDE_PROPERTY_CONTAINDISEASES 0
#define INCLUDE_CLASS_RANGINGSCALE 0
#define INCLUDE_CLASS_QUESTIONNAIRE 0
#define INCLUDE_CLASS_THING 0
#define INCLUDE_CLASS_ALARM 0
#define INCLUDE_CLASS_RESPONSETEXT 0
#define INCLUDE_CLASS_LOCATION 0
#define INCLUDE_CLASS_DICHOTOMOUS 0
#define INCLUDE_CLASS_HISREQUEST 0
#define INCLUDE_CLASS_CHOISE 0
#define INCLUDE_CLASS_PATIENTMETRICS 0
#define INCLUDE_CLASS_FEEDBACK 0
#define INCLUDE_CLASS_PHARMACY 0
#define INCLUDE_CLASS_GUTTMANSCALE 0
#define INCLUDE_CLASS_RESPONSEFILE 0
#define INCLUDE_CLASS_HISDOCUMENT 0
#define INCLUDE_CLASS_LABORATORYANALYSIS 0
#define INCLUDE_CLASS_RESPONSE 0
#define INCLUDE_CLASS_HISRESPONSE 0
#define INCLUDE_CLASS_DOCUMENT 0
#define INCLUDE_CLASS_BED 0
#define INCLUDE_CLASS_MEDIC 0
#define INCLUDE_CLASS_BLOODPRESSUREMEASUREMENT 0
#define INCLUDE_CLASS_ECGMEASUREMENT 0
#define INCLUDE_CLASS_USHSERVEY 0
#define INCLUDE_CLASS_CARING 0
#define INCLUDE_CLASS_PHONE 0
#define INCLUDE_CLASS_AMBULANCE 0
#define INCLUDE_CLASS_CLOSEDANSWER 0
#define INCLUDE_CLASS_HOSPITALINFORMATIONSYSTEM 0
#define INCLUDE_CLASS_DOCTOREXAMINATION 0
#define INCLUDE_CLASS_RESPONSEITEM 0
#define INCLUDE_CLASS_PATIENT 0
#define INCLUDE_CLASS_PERSON 0
#define INCLUDE_CLASS_AUTHREQUEST 0
#define INCLUDE_CLASS_PHOTO 0
#define INCLUDE_CLASS_DOCTOR 0
#define INCLUDE_CLASS_NURSE 0
#define INCLUDE_CLASS_LIKERTSCALE 0
#define INCLUDE_CLASS_AUDIO 0
#define INCLUDE_CLASS_CONTINUOUSSCALE 0
#define INCLUDE_CLASS_FILE 0
#define INCLUDE_CLASS_ADVICE 0
#define INCLUDE_CLASS_TEXT 0
#define INCLUDE_CLASS_MEDICALRECORDSCARD 0
#define INCLUDE_CLASS_ANSWER 0
#define INCLUDE_CLASS_NOTHING 0
#define INCLUDE_CLASS_MULTIPLECHOISE 0
#define INCLUDE_CLASS_ITEM 0
#define INCLUDE_CLASS_HOSPITAL 0
#define INCLUDE_CLASS_SERVEY 0
#define INCLUDE_CLASS_PROFILE 0
#define INCLUDE_CLASS_NUMBER 0
#define INCLUDE_CLASS_MEASUREMENT 0
#define INCLUDE_CLASS_VIDEO 0
#define INCLUDE_CLASS_DISEASE 0
#define INCLUDE_CLASS_ECGSERVEY 0
#define INCLUDE_CLASS_OPENANSWER 0
#define INCLUDE_CLASS_PATIENTMAP 0
#define INCLUDE_CLASS_QUESTION 0
#define INCLUDE_CLASS_DEMOGRAPHICDATA 0
#define INCLUDE_CLASS_EQUIPMENT 0
#define INCLUDE_CLASS_DRUG 0
#define INCLUDE_CLASS_SINGLECHOISE 0
#define INCLUDE_CLASS_VALIDATED 0
#define INCLUDE_CLASS_EMAIL 0
#define INCLUDE_CLASS_BIPOLARQUESTION 0


#endif


#if INCLUDE_CLASS_RANGINGSCALE
extern sslog_class_t *CLASS_RANGINGSCALE;
#endif
#if INCLUDE_CLASS_QUESTIONNAIRE
extern sslog_class_t *CLASS_QUESTIONNAIRE;
#endif
#if INCLUDE_CLASS_THING
extern sslog_class_t *CLASS_THING;
#endif
#if INCLUDE_CLASS_ALARM
extern sslog_class_t *CLASS_ALARM;
#endif
#if INCLUDE_CLASS_RESPONSETEXT
extern sslog_class_t *CLASS_RESPONSETEXT;
#endif
#if INCLUDE_CLASS_LOCATION
extern sslog_class_t *CLASS_LOCATION;
#endif
#if INCLUDE_CLASS_DICHOTOMOUS
extern sslog_class_t *CLASS_DICHOTOMOUS;
#endif
#if INCLUDE_CLASS_HISREQUEST
extern sslog_class_t *CLASS_HISREQUEST;
#endif
#if INCLUDE_CLASS_CHOISE
extern sslog_class_t *CLASS_CHOISE;
#endif
#if INCLUDE_CLASS_PATIENTMETRICS
extern sslog_class_t *CLASS_PATIENTMETRICS;
#endif
#if INCLUDE_CLASS_FEEDBACK
extern sslog_class_t *CLASS_FEEDBACK;
#endif
#if INCLUDE_CLASS_PHARMACY
extern sslog_class_t *CLASS_PHARMACY;
#endif
#if INCLUDE_CLASS_GUTTMANSCALE
extern sslog_class_t *CLASS_GUTTMANSCALE;
#endif
#if INCLUDE_CLASS_RESPONSEFILE
extern sslog_class_t *CLASS_RESPONSEFILE;
#endif
#if INCLUDE_CLASS_HISDOCUMENT
extern sslog_class_t *CLASS_HISDOCUMENT;
#endif
#if INCLUDE_CLASS_LABORATORYANALYSIS
extern sslog_class_t *CLASS_LABORATORYANALYSIS;
#endif
#if INCLUDE_CLASS_RESPONSE
extern sslog_class_t *CLASS_RESPONSE;
#endif
#if INCLUDE_CLASS_HISRESPONSE
extern sslog_class_t *CLASS_HISRESPONSE;
#endif
#if INCLUDE_CLASS_DOCUMENT
extern sslog_class_t *CLASS_DOCUMENT;
#endif
#if INCLUDE_CLASS_BED
extern sslog_class_t *CLASS_BED;
#endif
#if INCLUDE_CLASS_MEDIC
extern sslog_class_t *CLASS_MEDIC;
#endif
#if INCLUDE_CLASS_BLOODPRESSUREMEASUREMENT
extern sslog_class_t *CLASS_BLOODPRESSUREMEASUREMENT;
#endif
#if INCLUDE_CLASS_ECGMEASUREMENT
extern sslog_class_t *CLASS_ECGMEASUREMENT;
#endif
#if INCLUDE_CLASS_USHSERVEY
extern sslog_class_t *CLASS_USHSERVEY;
#endif
#if INCLUDE_CLASS_CARING
extern sslog_class_t *CLASS_CARING;
#endif
#if INCLUDE_CLASS_PHONE
extern sslog_class_t *CLASS_PHONE;
#endif
#if INCLUDE_CLASS_AMBULANCE
extern sslog_class_t *CLASS_AMBULANCE;
#endif
#if INCLUDE_CLASS_CLOSEDANSWER
extern sslog_class_t *CLASS_CLOSEDANSWER;
#endif
#if INCLUDE_CLASS_HOSPITALINFORMATIONSYSTEM
extern sslog_class_t *CLASS_HOSPITALINFORMATIONSYSTEM;
#endif
#if INCLUDE_CLASS_DOCTOREXAMINATION
extern sslog_class_t *CLASS_DOCTOREXAMINATION;
#endif
#if INCLUDE_CLASS_RESPONSEITEM
extern sslog_class_t *CLASS_RESPONSEITEM;
#endif
#if INCLUDE_CLASS_PATIENT
extern sslog_class_t *CLASS_PATIENT;
#endif
#if INCLUDE_CLASS_PERSON
extern sslog_class_t *CLASS_PERSON;
#endif
#if INCLUDE_CLASS_AUTHREQUEST
extern sslog_class_t *CLASS_AUTHREQUEST;
#endif
#if INCLUDE_CLASS_PHOTO
extern sslog_class_t *CLASS_PHOTO;
#endif
#if INCLUDE_CLASS_DOCTOR
extern sslog_class_t *CLASS_DOCTOR;
#endif
#if INCLUDE_CLASS_NURSE
extern sslog_class_t *CLASS_NURSE;
#endif
#if INCLUDE_CLASS_LIKERTSCALE
extern sslog_class_t *CLASS_LIKERTSCALE;
#endif
#if INCLUDE_CLASS_AUDIO
extern sslog_class_t *CLASS_AUDIO;
#endif
#if INCLUDE_CLASS_CONTINUOUSSCALE
extern sslog_class_t *CLASS_CONTINUOUSSCALE;
#endif
#if INCLUDE_CLASS_FILE
extern sslog_class_t *CLASS_FILE;
#endif
#if INCLUDE_CLASS_ADVICE
extern sslog_class_t *CLASS_ADVICE;
#endif
#if INCLUDE_CLASS_TEXT
extern sslog_class_t *CLASS_TEXT;
#endif
#if INCLUDE_CLASS_MEDICALRECORDSCARD
extern sslog_class_t *CLASS_MEDICALRECORDSCARD;
#endif
#if INCLUDE_CLASS_ANSWER
extern sslog_class_t *CLASS_ANSWER;
#endif
#if INCLUDE_CLASS_NOTHING
extern sslog_class_t *CLASS_NOTHING;
#endif
#if INCLUDE_CLASS_MULTIPLECHOISE
extern sslog_class_t *CLASS_MULTIPLECHOISE;
#endif
#if INCLUDE_CLASS_ITEM
extern sslog_class_t *CLASS_ITEM;
#endif
#if INCLUDE_CLASS_HOSPITAL
extern sslog_class_t *CLASS_HOSPITAL;
#endif
#if INCLUDE_CLASS_SERVEY
extern sslog_class_t *CLASS_SERVEY;
#endif
#if INCLUDE_CLASS_PROFILE
extern sslog_class_t *CLASS_PROFILE;
#endif
#if INCLUDE_CLASS_NUMBER
extern sslog_class_t *CLASS_NUMBER;
#endif
#if INCLUDE_CLASS_MEASUREMENT
extern sslog_class_t *CLASS_MEASUREMENT;
#endif
#if INCLUDE_CLASS_VIDEO
extern sslog_class_t *CLASS_VIDEO;
#endif
#if INCLUDE_CLASS_DISEASE
extern sslog_class_t *CLASS_DISEASE;
#endif
#if INCLUDE_CLASS_ECGSERVEY
extern sslog_class_t *CLASS_ECGSERVEY;
#endif
#if INCLUDE_CLASS_OPENANSWER
extern sslog_class_t *CLASS_OPENANSWER;
#endif
#if INCLUDE_CLASS_PATIENTMAP
extern sslog_class_t *CLASS_PATIENTMAP;
#endif
#if INCLUDE_CLASS_QUESTION
extern sslog_class_t *CLASS_QUESTION;
#endif
#if INCLUDE_CLASS_DEMOGRAPHICDATA
extern sslog_class_t *CLASS_DEMOGRAPHICDATA;
#endif
#if INCLUDE_CLASS_EQUIPMENT
extern sslog_class_t *CLASS_EQUIPMENT;
#endif
#if INCLUDE_CLASS_DRUG
extern sslog_class_t *CLASS_DRUG;
#endif
#if INCLUDE_CLASS_SINGLECHOISE
extern sslog_class_t *CLASS_SINGLECHOISE;
#endif
#if INCLUDE_CLASS_VALIDATED
extern sslog_class_t *CLASS_VALIDATED;
#endif
#if INCLUDE_CLASS_EMAIL
extern sslog_class_t *CLASS_EMAIL;
#endif
#if INCLUDE_CLASS_BIPOLARQUESTION
extern sslog_class_t *CLASS_BIPOLARQUESTION;
#endif


#if INCLUDE_PROPERTY_HASSTATIONAREQUIPMENT
extern sslog_property_t *PROPERTY_HASSTATIONAREQUIPMENT;
#endif
#if INCLUDE_PROPERTY_TAKEDRUGTIME
extern sslog_property_t *PROPERTY_TAKEDRUGTIME;
#endif
#if INCLUDE_PROPERTY_HASPATIENTMAP
extern sslog_property_t *PROPERTY_HASPATIENTMAP;
#endif
#if INCLUDE_PROPERTY_EXAMINATIONREASON
extern sslog_property_t *PROPERTY_EXAMINATIONREASON;
#endif
#if INCLUDE_PROPERTY_RESPONSETOALARM
extern sslog_property_t *PROPERTY_RESPONSETOALARM;
#endif
#if INCLUDE_PROPERTY_ISPATIENTDRUGADDICTED
extern sslog_property_t *PROPERTY_ISPATIENTDRUGADDICTED;
#endif
#if INCLUDE_PROPERTY_RESPONSEFILEURI
extern sslog_property_t *PROPERTY_RESPONSEFILEURI;
#endif
#if INCLUDE_PROPERTY_QUESTIONNAIREURI
extern sslog_property_t *PROPERTY_QUESTIONNAIREURI;
#endif
#if INCLUDE_PROPERTY_LEFTBIPOLAR
extern sslog_property_t *PROPERTY_LEFTBIPOLAR;
#endif
#if INCLUDE_PROPERTY_USEEQUIPMENTTIME
extern sslog_property_t *PROPERTY_USEEQUIPMENTTIME;
#endif
#if INCLUDE_PROPERTY_USERNAME
extern sslog_property_t *PROPERTY_USERNAME;
#endif
#if INCLUDE_PROPERTY_DATALOCATION
extern sslog_property_t *PROPERTY_DATALOCATION;
#endif
#if INCLUDE_PROPERTY_FIELDNAME
extern sslog_property_t *PROPERTY_FIELDNAME;
#endif
#if INCLUDE_PROPERTY_ISONLINE
extern sslog_property_t *PROPERTY_ISONLINE;
#endif
#if INCLUDE_PROPERTY_EQUIPPARAMETER
extern sslog_property_t *PROPERTY_EQUIPPARAMETER;
#endif
#if INCLUDE_PROPERTY_SEX
extern sslog_property_t *PROPERTY_SEX;
#endif
#if INCLUDE_PROPERTY_PASSAUTH
extern sslog_property_t *PROPERTY_PASSAUTH;
#endif
#if INCLUDE_PROPERTY_HASDRUGTOSAVE
extern sslog_property_t *PROPERTY_HASDRUGTOSAVE;
#endif
#if INCLUDE_PROPERTY_FREEPATIENTCAPACITY
extern sslog_property_t *PROPERTY_FREEPATIENTCAPACITY;
#endif
#if INCLUDE_PROPERTY_IMG
extern sslog_property_t *PROPERTY_IMG;
#endif
#if INCLUDE_PROPERTY_HASDOCTOR
extern sslog_property_t *PROPERTY_HASDOCTOR;
#endif
#if INCLUDE_PROPERTY_RELATESTO
extern sslog_property_t *PROPERTY_RELATESTO;
#endif
#if INCLUDE_PROPERTY_READYTOHELP
extern sslog_property_t *PROPERTY_READYTOHELP;
#endif
#if INCLUDE_PROPERTY_CONTAINSSUBRESPONSE
extern sslog_property_t *PROPERTY_CONTAINSSUBRESPONSE;
#endif
#if INCLUDE_PROPERTY_CONTAINSFILE
extern sslog_property_t *PROPERTY_CONTAINSFILE;
#endif
#if INCLUDE_PROPERTY_PATIENTWEIGHT
extern sslog_property_t *PROPERTY_PATIENTWEIGHT;
#endif
#if INCLUDE_PROPERTY_TOPDATAPROPERTY
extern sslog_property_t *PROPERTY_TOPDATAPROPERTY;
#endif
#if INCLUDE_PROPERTY_HOSPITALNAME
extern sslog_property_t *PROPERTY_HOSPITALNAME;
#endif
#if INCLUDE_PROPERTY_HEIGHT
extern sslog_property_t *PROPERTY_HEIGHT;
#endif
#if INCLUDE_PROPERTY_RESIDENCE
extern sslog_property_t *PROPERTY_RESIDENCE;
#endif
#if INCLUDE_PROPERTY_DRINKING
extern sslog_property_t *PROPERTY_DRINKING;
#endif
#if INCLUDE_PROPERTY_CARNUMBER
extern sslog_property_t *PROPERTY_CARNUMBER;
#endif
#if INCLUDE_PROPERTY_ITEMTEXT
extern sslog_property_t *PROPERTY_ITEMTEXT;
#endif
#if INCLUDE_PROPERTY_SMOKING
extern sslog_property_t *PROPERTY_SMOKING;
#endif
#if INCLUDE_PROPERTY_SENDALARM
extern sslog_property_t *PROPERTY_SENDALARM;
#endif
#if INCLUDE_PROPERTY_HASDRUGTOMEDICINE
extern sslog_property_t *PROPERTY_HASDRUGTOMEDICINE;
#endif
#if INCLUDE_PROPERTY_FEEDBACKURI
extern sslog_property_t *PROPERTY_FEEDBACKURI;
#endif
#if INCLUDE_PROPERTY_SPECIALLITY
extern sslog_property_t *PROPERTY_SPECIALLITY;
#endif
#if INCLUDE_PROPERTY_HASQUESTION
extern sslog_property_t *PROPERTY_HASQUESTION;
#endif
#if INCLUDE_PROPERTY_ADVICETEXT
extern sslog_property_t *PROPERTY_ADVICETEXT;
#endif
#if INCLUDE_PROPERTY_LOCATION
extern sslog_property_t *PROPERTY_LOCATION;
#endif
#if INCLUDE_PROPERTY_HASDRUGTOTAKE
extern sslog_property_t *PROPERTY_HASDRUGTOTAKE;
#endif
#if INCLUDE_PROPERTY_HASMEDICALRECORDSCARD
extern sslog_property_t *PROPERTY_HASMEDICALRECORDSCARD;
#endif
#if INCLUDE_PROPERTY_MEDICATIONS
extern sslog_property_t *PROPERTY_MEDICATIONS;
#endif
#if INCLUDE_PROPERTY_HASACCESS
extern sslog_property_t *PROPERTY_HASACCESS;
#endif
#if INCLUDE_PROPERTY_MULTIPLEITEM
extern sslog_property_t *PROPERTY_MULTIPLEITEM;
#endif
#if INCLUDE_PROPERTY_CONTAINECGSURVEYS
extern sslog_property_t *PROPERTY_CONTAINECGSURVEYS;
#endif
#if INCLUDE_PROPERTY_DICHOTOMOUSITEM
extern sslog_property_t *PROPERTY_DICHOTOMOUSITEM;
#endif
#if INCLUDE_PROPERTY_HASRESPONSEITEM
extern sslog_property_t *PROPERTY_HASRESPONSEITEM;
#endif
#if INCLUDE_PROPERTY_RIGHTBIPOLAR
extern sslog_property_t *PROPERTY_RIGHTBIPOLAR;
#endif
#if INCLUDE_PROPERTY_DRUGNAME
extern sslog_property_t *PROPERTY_DRUGNAME;
#endif
#if INCLUDE_PROPERTY_SENDADVICE
extern sslog_property_t *PROPERTY_SENDADVICE;
#endif
#if INCLUDE_PROPERTY_CONTACTINFORMATION
extern sslog_property_t *PROPERTY_CONTACTINFORMATION;
#endif
#if INCLUDE_PROPERTY_HASDOCUMENT
extern sslog_property_t *PROPERTY_HASDOCUMENT;
#endif
#if INCLUDE_PROPERTY_ISPATIENTMEDICINEADDICTED
extern sslog_property_t *PROPERTY_ISPATIENTMEDICINEADDICTED;
#endif
#if INCLUDE_PROPERTY_SEARCHSTRING
extern sslog_property_t *PROPERTY_SEARCHSTRING;
#endif
#if INCLUDE_PROPERTY_SERVEYDATE
extern sslog_property_t *PROPERTY_SERVEYDATE;
#endif
#if INCLUDE_PROPERTY_HEMATOCRIT
extern sslog_property_t *PROPERTY_HEMATOCRIT;
#endif
#if INCLUDE_PROPERTY_AGE
extern sslog_property_t *PROPERTY_AGE;
#endif
#if INCLUDE_PROPERTY_ALARMSTATUS
extern sslog_property_t *PROPERTY_ALARMSTATUS;
#endif
#if INCLUDE_PROPERTY_DRUGANNOTATION
extern sslog_property_t *PROPERTY_DRUGANNOTATION;
#endif
#if INCLUDE_PROPERTY_PATIENTBLOODTYPE
extern sslog_property_t *PROPERTY_PATIENTBLOODTYPE;
#endif
#if INCLUDE_PROPERTY_PHARMNAME
extern sslog_property_t *PROPERTY_PHARMNAME;
#endif
#if INCLUDE_PROPERTY_ITEMSCORE
extern sslog_property_t *PROPERTY_ITEMSCORE;
#endif
#if INCLUDE_PROPERTY_HASFEEDBACK
extern sslog_property_t *PROPERTY_HASFEEDBACK;
#endif
#if INCLUDE_PROPERTY_HASPERSLOCATION
extern sslog_property_t *PROPERTY_HASPERSLOCATION;
#endif
#if INCLUDE_PROPERTY_ORGANIZATIONNAME
extern sslog_property_t *PROPERTY_ORGANIZATIONNAME;
#endif
#if INCLUDE_PROPERTY_PATIENTRHFACTOR
extern sslog_property_t *PROPERTY_PATIENTRHFACTOR;
#endif
#if INCLUDE_PROPERTY_SURVEYECGINFO
extern sslog_property_t *PROPERTY_SURVEYECGINFO;
#endif
#if INCLUDE_PROPERTY_CONTAINUSHSURVEYS
extern sslog_property_t *PROPERTY_CONTAINUSHSURVEYS;
#endif
#if INCLUDE_PROPERTY_REQUESTSDOCUMENT
extern sslog_property_t *PROPERTY_REQUESTSDOCUMENT;
#endif
#if INCLUDE_PROPERTY_SINGLEITEM
extern sslog_property_t *PROPERTY_SINGLEITEM;
#endif
#if INCLUDE_PROPERTY_PATRONYMIC
extern sslog_property_t *PROPERTY_PATRONYMIC;
#endif
#if INCLUDE_PROPERTY_HASAMBLOCATION
extern sslog_property_t *PROPERTY_HASAMBLOCATION;
#endif
#if INCLUDE_PROPERTY_DISEASEDESCRIPTION
extern sslog_property_t *PROPERTY_DISEASEDESCRIPTION;
#endif
#if INCLUDE_PROPERTY_HASDRUGTOSALE
extern sslog_property_t *PROPERTY_HASDRUGTOSALE;
#endif
#if INCLUDE_PROPERTY_DATEFROM
extern sslog_property_t *PROPERTY_DATEFROM;
#endif
#if INCLUDE_PROPERTY_TOPOBJECTPROPERTY
extern sslog_property_t *PROPERTY_TOPOBJECTPROPERTY;
#endif
#if INCLUDE_PROPERTY_HEMOGLOBIN
extern sslog_property_t *PROPERTY_HEMOGLOBIN;
#endif
#if INCLUDE_PROPERTY_CONTAINSTEXT
extern sslog_property_t *PROPERTY_CONTAINSTEXT;
#endif
#if INCLUDE_PROPERTY_SERVEYRESULT
extern sslog_property_t *PROPERTY_SERVEYRESULT;
#endif
#if INCLUDE_PROPERTY_PATIENTHEIGHT
extern sslog_property_t *PROPERTY_PATIENTHEIGHT;
#endif
#if INCLUDE_PROPERTY_WORKHOSPITAL
extern sslog_property_t *PROPERTY_WORKHOSPITAL;
#endif
#if INCLUDE_PROPERTY_PHONE
extern sslog_property_t *PROPERTY_PHONE;
#endif
#if INCLUDE_PROPERTY_ALARMTIME
extern sslog_property_t *PROPERTY_ALARMTIME;
#endif
#if INCLUDE_PROPERTY_HASHOSPLOCATION
extern sslog_property_t *PROPERTY_HASHOSPLOCATION;
#endif
#if INCLUDE_PROPERTY_SUBANSWER
extern sslog_property_t *PROPERTY_SUBANSWER;
#endif
#if INCLUDE_PROPERTY_DIAGNOSES
extern sslog_property_t *PROPERTY_DIAGNOSES;
#endif
#if INCLUDE_PROPERTY_RANGINGITEM
extern sslog_property_t *PROPERTY_RANGINGITEM;
#endif
#if INCLUDE_PROPERTY_HASREQUEST
extern sslog_property_t *PROPERTY_HASREQUEST;
#endif
#if INCLUDE_PROPERTY_PULSE
extern sslog_property_t *PROPERTY_PULSE;
#endif
#if INCLUDE_PROPERTY_CODE
extern sslog_property_t *PROPERTY_CODE;
#endif
#if INCLUDE_PROPERTY_RESPONDEDTO
extern sslog_property_t *PROPERTY_RESPONDEDTO;
#endif
#if INCLUDE_PROPERTY_DISEASEPREDISPOSITION
extern sslog_property_t *PROPERTY_DISEASEPREDISPOSITION;
#endif
#if INCLUDE_PROPERTY_DESCRIPTION
extern sslog_property_t *PROPERTY_DESCRIPTION;
#endif
#if INCLUDE_PROPERTY_HASANSWER
extern sslog_property_t *PROPERTY_HASANSWER;
#endif
#if INCLUDE_PROPERTY_HASPHARMLOCATION
extern sslog_property_t *PROPERTY_HASPHARMLOCATION;
#endif
#if INCLUDE_PROPERTY_SERVEYDATALINK
extern sslog_property_t *PROPERTY_SERVEYDATALINK;
#endif
#if INCLUDE_PROPERTY_CREATEDAT
extern sslog_property_t *PROPERTY_CREATEDAT;
#endif
#if INCLUDE_PROPERTY_ISPATIENTSMOKE
extern sslog_property_t *PROPERTY_ISPATIENTSMOKE;
#endif
#if INCLUDE_PROPERTY_AUTHOR
extern sslog_property_t *PROPERTY_AUTHOR;
#endif
#if INCLUDE_PROPERTY_VISITORDER
extern sslog_property_t *PROPERTY_VISITORDER;
#endif
#if INCLUDE_PROPERTY_DIASTOLICPRESSURE
extern sslog_property_t *PROPERTY_DIASTOLICPRESSURE;
#endif
#if INCLUDE_PROPERTY_SYSTOLICPRESSURE
extern sslog_property_t *PROPERTY_SYSTOLICPRESSURE;
#endif
#if INCLUDE_PROPERTY_BELONGSTO
extern sslog_property_t *PROPERTY_BELONGSTO;
#endif
#if INCLUDE_PROPERTY_HASPATIENTMETRICS
extern sslog_property_t *PROPERTY_HASPATIENTMETRICS;
#endif
#if INCLUDE_PROPERTY_DOSAGE
extern sslog_property_t *PROPERTY_DOSAGE;
#endif
#if INCLUDE_PROPERTY_LINKEDWITHITEM
extern sslog_property_t *PROPERTY_LINKEDWITHITEM;
#endif
#if INCLUDE_PROPERTY_SERVEYTYPE
extern sslog_property_t *PROPERTY_SERVEYTYPE;
#endif
#if INCLUDE_PROPERTY_DOCUMENTNUMBERFULL
extern sslog_property_t *PROPERTY_DOCUMENTNUMBERFULL;
#endif
#if INCLUDE_PROPERTY_LONG
extern sslog_property_t *PROPERTY_LONG;
#endif
#if INCLUDE_PROPERTY_HISID
extern sslog_property_t *PROPERTY_HISID;
#endif
#if INCLUDE_PROPERTY_FIRSTQUESTION
extern sslog_property_t *PROPERTY_FIRSTQUESTION;
#endif
#if INCLUDE_PROPERTY_ANWEREDTO
extern sslog_property_t *PROPERTY_ANWEREDTO;
#endif
#if INCLUDE_PROPERTY_ISPATIENTALCOHOLADDICTED
extern sslog_property_t *PROPERTY_ISPATIENTALCOHOLADDICTED;
#endif
#if INCLUDE_PROPERTY_SERVEYDESCRIPTION
extern sslog_property_t *PROPERTY_SERVEYDESCRIPTION;
#endif
#if INCLUDE_PROPERTY_DOCUMENTTYPE
extern sslog_property_t *PROPERTY_DOCUMENTTYPE;
#endif
#if INCLUDE_PROPERTY_LAT
extern sslog_property_t *PROPERTY_LAT;
#endif
#if INCLUDE_PROPERTY_SURNAME
extern sslog_property_t *PROPERTY_SURNAME;
#endif
#if INCLUDE_PROPERTY_HASRESPONSE
extern sslog_property_t *PROPERTY_HASRESPONSE;
#endif
#if INCLUDE_PROPERTY_DOCUMENTRELEASEDATE
extern sslog_property_t *PROPERTY_DOCUMENTRELEASEDATE;
#endif
#if INCLUDE_PROPERTY_PERSONINFORMATION
extern sslog_property_t *PROPERTY_PERSONINFORMATION;
#endif
#if INCLUDE_PROPERTY_AUTHREQUESTSTATUS
extern sslog_property_t *PROPERTY_AUTHREQUESTSTATUS;
#endif
#if INCLUDE_PROPERTY_RESPONSETEXT
extern sslog_property_t *PROPERTY_RESPONSETEXT;
#endif
#if INCLUDE_PROPERTY_PASSWORD
extern sslog_property_t *PROPERTY_PASSWORD;
#endif
#if INCLUDE_PROPERTY_WEIGHT
extern sslog_property_t *PROPERTY_WEIGHT;
#endif
#if INCLUDE_PROPERTY_BIRTHDATE
extern sslog_property_t *PROPERTY_BIRTHDATE;
#endif
#if INCLUDE_PROPERTY_MBOX
extern sslog_property_t *PROPERTY_MBOX;
#endif
#if INCLUDE_PROPERTY_HASPORTABLEEQUIPMENT
extern sslog_property_t *PROPERTY_HASPORTABLEEQUIPMENT;
#endif
#if INCLUDE_PROPERTY_DESCRIBES
extern sslog_property_t *PROPERTY_DESCRIBES;
#endif
#if INCLUDE_PROPERTY_VERSION
extern sslog_property_t *PROPERTY_VERSION;
#endif
#if INCLUDE_PROPERTY_DATETO
extern sslog_property_t *PROPERTY_DATETO;
#endif
#if INCLUDE_PROPERTY_WORKAMBULANCE
extern sslog_property_t *PROPERTY_WORKAMBULANCE;
#endif
#if INCLUDE_PROPERTY_NEXTQUESTION
extern sslog_property_t *PROPERTY_NEXTQUESTION;
#endif
#if INCLUDE_PROPERTY_FEEDBACKDATE
extern sslog_property_t *PROPERTY_FEEDBACKDATE;
#endif
#if INCLUDE_PROPERTY_NAME
extern sslog_property_t *PROPERTY_NAME;
#endif
#if INCLUDE_PROPERTY_HASERROR
extern sslog_property_t *PROPERTY_HASERROR;
#endif
#if INCLUDE_PROPERTY_STATUS
extern sslog_property_t *PROPERTY_STATUS;
#endif
#if INCLUDE_PROPERTY_ADVICETIME
extern sslog_property_t *PROPERTY_ADVICETIME;
#endif
#if INCLUDE_PROPERTY_ERYTHROCYTE
extern sslog_property_t *PROPERTY_ERYTHROCYTE;
#endif
#if INCLUDE_PROPERTY_DISEASETYPE
extern sslog_property_t *PROPERTY_DISEASETYPE;
#endif
#if INCLUDE_PROPERTY_SERVEYUSHINFO
extern sslog_property_t *PROPERTY_SERVEYUSHINFO;
#endif
#if INCLUDE_PROPERTY_CONTAINDISEASES
extern sslog_property_t *PROPERTY_CONTAINDISEASES;
#endif



void register_ontology();

	
#ifdef	__cplusplus
}
#endif

#endif /* _GENERATED_ONTOLOGY */
